led.enable(false)
loops.everyInterval(randint(1000, 4000), function () {
    pins.digitalWritePin(DigitalPin.P9, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P9, 0)
    pins.digitalWritePin(DigitalPin.P10, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P10, 0)
    pins.digitalWritePin(DigitalPin.P13, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P13, 0)
    pins.digitalWritePin(DigitalPin.P12, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P12, 0)
})
loops.everyInterval(10000, function () {
    pins.digitalWritePin(DigitalPin.P12, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P12, 0)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P12, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P12, 0)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P12, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P12, 0)
    basic.pause(50)
})
